SELECT
    TARGET,

    COUNT(*) AS MUSTERI_SAYISI,

    -- Müşterinin geçmiş kredi / taksit yoğunluğu
    ROUND(AVG(TOPLAM_TAKSIT_SAYISI), 2) AS ORT_TOPLAM_TAKSIT_SAYISI,
    ROUND(AVG(ESKI_KREDI_SAYISI), 2) AS ORT_ESKI_KREDI_SAYISI,

    -- Ödeme davranışları
    ROUND(AVG(GEC_ODEME_SAYISI), 2) AS ORT_GEC_ODEME_SAYISI,
    ROUND(AVG(ZAMANINDA_ODEME_SAYISI), 2) AS ORT_ZAMANINDA_ODEME_SAYISI,
    ROUND(AVG(ERKEN_ODEME_SAYISI), 2) AS ORT_ERKEN_ODEME_SAYISI,
    ROUND(AVG(EKSIK_ODEME_SAYISI), 2) AS ORT_EKSIK_ODEME_SAYISI,

    -- Taksit oran KPI'ları
    ROUND(AVG(TAKSIT_GEC_ODEME_ORANI), 2)
        AS ORT_TAKSIT_GEC_ODEME_ORANI,

    ROUND(AVG(TAKSIT_EKSIK_ODEME_ORANI), 2)
        AS ORT_TAKSIT_EKSIK_ODEME_ORANI,

    -- Taksit gecikmesinin büyüklüğü
    ROUND(AVG(TAKSIT_ORT_GECIKME_GUNU), 2)
        AS ORT_TAKSIT_GECIKME_GUNU,

    ROUND(AVG(TAKSIT_MAKS_GECIKME_GUNU), 2)
        AS ORT_TAKSIT_MAKS_GECIKME_GUNU

FROM {{ ref('mart_meric_target_kpi_analysis') }}

GROUP BY TARGET

ORDER BY TARGET