SELECT
    TARGET,

    COUNT(*) AS MUSTERI_SAYISI,

    ROUND(AVG(KART_GECIKMELI_AY_ORANI), 2)
        AS ORT_KART_GECIKMELI_AY_ORANI,

    ROUND(AVG(KART_TOLERANS_SONRASI_GECIKME_ORANI), 2)
        AS ORT_KART_TOLERANS_SONRASI_GECIKME_ORANI,

    ROUND(AVG(KART_MAKS_GECIKME_GUNU), 2)
        AS ORT_KART_MAKS_GECIKME_GUNU,

    ROUND(AVG(KART_ORT_BORC_BAKIYESI), 2)
        AS ORT_KART_BORC_BAKIYESI,

    ROUND(AVG(KART_MAKS_BORC_BAKIYESI), 2)
        AS ORT_KART_MAKS_BORC_BAKIYESI,

    ROUND(AVG(KART_ORT_LIMIT_KULLANIM_ORANI), 2)
        AS ORT_KART_LIMIT_KULLANIM_ORANI,

    ROUND(AVG(KART_LIMIT_ASIMLI_AY_ORANI), 2)
        AS ORT_KART_LIMIT_ASIMLI_AY_ORANI

FROM {{ ref('mart_meric_target_kpi_analysis') }}

GROUP BY TARGET

ORDER BY TARGET