SELECT
    a.*,

    -- INSTALLMENTS KPI'LARI
    i.TOPLAM_TAKSIT_SAYISI,
    i.ESKI_KREDI_SAYISI,
    i.GEC_ODEME_SAYISI,
    i.ZAMANINDA_ODEME_SAYISI,
    i.ERKEN_ODEME_SAYISI,
    i.EKSIK_ODEME_SAYISI,

    i.GEC_ODEME_ORANI AS TAKSIT_GEC_ODEME_ORANI,
    i.EKSIK_ODEME_ORANI AS TAKSIT_EKSIK_ODEME_ORANI,
    i.ORTALAMA_GECIKME_GUNU AS TAKSIT_ORT_GECIKME_GUNU,
    i.MAKS_GECIKME_GUNU AS TAKSIT_MAKS_GECIKME_GUNU,


    -- CREDIT CARD KPI'LARI
    c.AYLIK_KAYIT_SAYISI AS KART_AYLIK_KAYIT_SAYISI,
    c.GECIKMELI_AY_SAYISI AS KART_GECIKMELI_AY_SAYISI,
    c.GECIKMELI_AY_ORANI AS KART_GECIKMELI_AY_ORANI,

    c.TOLERANS_SONRASI_GECIKMELI_AY_SAYISI
        AS KART_TOLERANS_SONRASI_GECIKMELI_AY_SAYISI,

    c.TOLERANS_SONRASI_GECIKME_ORANI
        AS KART_TOLERANS_SONRASI_GECIKME_ORANI,

    c.MAKS_GECIKME_GUNU
        AS KART_MAKS_GECIKME_GUNU,

    c.ORTALAMA_BORC_BAKIYESI
        AS KART_ORT_BORC_BAKIYESI,

    c.MAKS_BORC_BAKIYESI
        AS KART_MAKS_BORC_BAKIYESI,

    c.ORTALAMA_LIMIT_KULLANIM_ORANI
        AS KART_ORT_LIMIT_KULLANIM_ORANI,

    c.LIMIT_ASIMLI_AY_ORANI
        AS KART_LIMIT_ASIMLI_AY_ORANI


FROM {{ ref('int_application_train_features') }} AS a

LEFT JOIN {{ ref('int_installments_customer_features') }} AS i
    ON a.SK_ID_CURR = i.SK_ID_CURR

LEFT JOIN {{ ref('int_credit_card_features') }} AS c
    ON a.SK_ID_CURR = c.SK_ID_CURR